apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata: 
  name: prometheus-tls-secret
data: 
  tls.crt: "{{ prometheus_tls_secret_cert }}"
  tls.key: "{{ prometheus_tls_secret_key }}"

---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata: 
  name: alertmanager-tls-secret
data: 
  tls.crt: "{{ alertmanager_tls_secret_cert }}"
  tls.key: "{{ alertmanager_tls_secret_key }}"
