server:
  # see https://github.com/prometheus-community/helm-charts/issues/1594
  # if changing prefixURL or baseURL
  # prefixURL: /
  baseURL: http://{{ prometheus_ingress_host }}
  persistentVolume:
    size: "{{ prometheus_volume_size_gb }}Gi"
    storageClass: {{ kube_storageclass_prometheus }}
  ingress:
    enabled: true
    ingressClassName: {{ prometheus_ingress_class }}
    annotations:
      kubernetes.io/ingress.class: "nginx"
    hosts:
      - {{ prometheus_ingress_host }}
    tls:
      - secretName: prometheus-tls-secret
        hosts:
          - {{ prometheus_ingress_host }}
                
#    hosts:
#      - host: {{ prometheus_ingress_host }}
#        paths:
#          - path: /
#            pathType: ImplementationSpecific

                 
alertmanager:
  # even within the same chart they can't use the same goddamn key
  persistence:
    size: "{{ alertmanager_volume_size_gb }}Gi"
    storageClass: {{ kube_storageclass_prometheus }}
  ingress:
    enabled: true
    ingressClassName: {{ prometheus_ingress_class }}
    hosts:
      - host: {{ alertmanager_ingress_host }}
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: alertmanager-tls-secret
        hosts:
          - {{ alertmanager_ingress_host }}
                