server:
  baseURL: http://{{ prometheus_ingress_host }}
  persistentVolume:
    size: "{{ prometheus_volume_size_gb }}Gi"
    storageClass: {{ kube_storageclass_prometheus }}
  ingress:
    enabled: true
    ingressClassName: {{ prometheus_ingress_class }}
    annotations:
      kubernetes.io/ingress.class: "nginx"
    hosts:
      - {{ prometheus_ingress_host }}
    tls:
      - secretName: prometheus-tls-secret
        hosts:
          - {{ prometheus_ingress_host }}
                 
alertmanager:
  # note different key to 'server' above
  persistence:
    size: "{{ alertmanager_volume_size_gb }}Gi"
    storageClass: {{ kube_storageclass_prometheus }}
  ingress:
    enabled: true
    ingressClassName: {{ prometheus_ingress_class }}
    hosts:
      - host: {{ alertmanager_ingress_host }}
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: alertmanager-tls-secret
        hosts:
          - {{ alertmanager_ingress_host }}
                