ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
  hosts:
    - {{ grafana_ingress_host }}
  tls:
    - secretName: grafana-tls-secret
      hosts:
        - {{ grafana_ingress_host }}

persistence:
  enabled: true
  size: "{{ grafana_volume_size_gb }}Gi"
  storageClassName: {{ kube_storageclass_grafana }}

# administrator credentials when not using an existing secret
adminUser: admin
adminPassword: abc123