# k8s yaml based on the official image at https://hub.docker.com/r/ollama/ollama

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-pvc
spec:
  storageClassName: "{{ kube_storageclass_ollama }}"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ ollama_volume_size_gb }}Gi"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama-web
  template:
    metadata:
      labels:
        app: ollama-web
    spec:
      nodeSelector:
        {{ ollama_gpu_node_selector_key }}: "{{ ollama_gpu_node_selector_value }}"
      runtimeClassName: "{{ ollama_gpu_runtime_class_name }}"
      containers:
        - name: ollama
          image: ollama/ollama:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 11434
          env:
            - name: OLLAMA_HOST
              value: "0.0.0.0:11434"
          resources:
            limits:
              cpu: "{{ ollama_cpu_limit }}"
              memory: "{{ ollama_memory_limit }}"
              nvidia.com/gpu: "{{ ollama_gpu_count }}"
            requests:
              cpu: "{{ ollama_cpu_request }}"
              memory: "{{ ollama_memory_request }}"
              nvidia.com/gpu: "{{ ollama_gpu_count }}"
          volumeMounts:
            - mountPath: /root/.ollama
              name: models
      volumes:
        - name: models
          persistentVolumeClaim:
            claimName: ollama-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: ollama-web
  ports:
    - protocol: TCP
      port: 11434
      targetPort: 11434
  type: LoadBalancer
