- hosts: localhost
  gather_facts: false
  vars:
    k8s_apps_bnekub02:
      deployments:
        - name: gitlab-bnekub02
          role: gitlab
          var_files: [bnekub02]
        - name: xwiki-bnekub02
          role: xwiki
          var_files: [bnekub02]
        - name: nexus2-bnekub02
          role: nexus2
          var_files: [bnekub02]
        - name: nexus3-bnekub02
          role: nexus3
          var_files: [bnekub02]

  tasks:
    - name: deploy apps
      include_tasks: apply_role.yml
      vars:
        apply_role_name: "{{ _k8s_apps_bnekub02_deployment.0.role }}"
        apply_role_var_files: "{{ _k8s_apps_bnekub02_deployment.0.var_files }}"
      loop: "{{ k8s_apps_bnekub02.deployments | product(deployments.split(',')) | list }}"
      loop_control: { loop_var: _k8s_apps_bnekub02_deployment }
      when:
        - deployments is not defined or true      

