kube_context_xwiki: "bnekub02"
kube_storageclass_xwiki: "bnenas04-nfs-csi"

xwiki_ingress_host: "wiki.dev.randomnoun"
xwiki_ingress_class: "nginx-internal"

xwiki_tls_secret_cert: "{{ lookup('hashi_vault', 'mount_point=secret secret=secret/data/k8s/bnekub02/secret/dev-xwiki/xwiki-tls-secret:tls.crt')}}"
xwiki_tls_secret_key: "{{ lookup('hashi_vault', 'mount_point=secret secret=secret/data/k8s/bnekub02/secret/dev-xwiki/xwiki-tls-secret:tls.key')}}"

xwiki_volume_size_gb: 40
