kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: nginx-ingress
data:
# default log-format from https://github.com/nginxinc/kubernetes-ingress/blob/v1.8.0/internal/configs/version1/nginx.tmpl
#  log-format: "$remote_addr - $remote_user [$time_local] \"$request\" $status $body_bytes_sent \"$http_referer\" \"$http_user_agent\" \"$http_x_forwarded_for\""
# vars are listed at http://nginx.org/en/docs/http/ngx_http_log_module.html
# and http://nginx.org/en/docs/varindex.html
# going to shove the hostname into the 'user-identifier' field of the NCSA common log
  log-format: "$remote_addr $host:$server_port $ssl_protocol [$time_local] \"$request\" $status $body_bytes_sent \"$http_referer\" \"$http_user_agent\" \"$http_x_forwarded_for\""
  